//Solicitar a usuario año de nacimiento y retornar edad que tendrá al finalizar el año...

package demoFiles; //Paquete al que pertenece esta clase...

import java.util.Scanner; //Importando clases de librerías que serán utilizadas en la aplicación...

public class Edad {
	public static void main(String[] args) 
	{
		Scanner entrada = new Scanner(System.in); //Instancia de la clase Scanner que nos permitirá obtener lo que digite el usuario...
		final int ANIO_ACTUAL=2020; //Variale constante que contiene el año actual... Este tipo de variables no cambian su valor a lo largo de la aplicación...
		int anioNacimiento, edad; //Declaración de variables locales...
		System.out.print("Digite su año de nacimiento: ");
		anioNacimiento=entrada.nextInt(); //Asignando a la variable lo que digitó el usuario...
		edad=ANIO_ACTUAL-anioNacimiento; //Realizando operación que obtendrá la edad al finalizar el año del usuario...
		System.out.print("Al finalizar el año usted tendrá: " + edad + " años."); //Imprimiendo la edad que tendrá el usuario al finalizar el año...
		entrada.close(); //Se cierra la instancia de la clase Scanner
	}
}