//Solicitar al usuario su primer nombre y su primer apellido y a partir de esto retornar el nombre completo...

package demoFiles; //Paquete al que pertenece esta clase...

import java.util.Scanner; //Importando clases de librerías que serán utilizadas en la aplicación...

public class NombreCompleto {
	public static void main(String[] args) 
	{
		Scanner entrada = new Scanner(System.in); //Instancia de la clase Scanner que nos permitirá obtener lo que digite el usuario...
		String pNombre, pApellido;	//Declaración de variables locales...
		System.out.print("Digite el primer nombre: ");
		pNombre=entrada.next(); //Asignando a la variable lo que digitó el usuario...
		System.out.print("Digite el primer apellido: ");
		pApellido=entrada.next(); //Asignando a la variable lo que digitó el usuario...
		System.out.print("Su nombre completo es: " + pNombre + " " + pApellido); //Imprimiendo el nombre completo del usuario...
		entrada.close(); //Se cierra la instancia de la clase Scanner
	}
}